/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Pointer to the schema against which this document should be validated.
 */
export type Schema = string;
/**
 * Parameter definition
 *
 */
export type ParameterDefinition = AlignmentParameterDefinition | AnimationParameterDefinition | Asset3DParameterDefinition | AudioParameterDefinition | BooleanParameterDefinition | ColorParameterDefinition | FontFamilyParameterDefinition | FormattedTextParameterDefinition | ImageParameterDefinition | NumberParameterDefinition | ObjectParameterDefinition | PositionParameterDefinition | RangeParameterDefinition | SelectParameterDefinition | TextParameterDefinition | VideoParameterDefinition;
/**
 * highlightable parameter value
 *
 * @devPortal
 *
 */
export type HighlightParameterValue = boolean;
/**
 * relative path from the playable.json to a 3d asset file
 *
 */
export type Asset3DParameterValue = string;
/**
 * Hex representation of a color (ex: #ffffff)
 *
 */
export type ColorParameterValue = string;
/**
 * A number
 *
 */
export type NumberParameterValue = number;
/**
 * A string
 *
 */
export type TextParameterValue = string;
/**
 * relative path from the playable.json to an audio file
 *
 */
export type AudioParameterValue = string;
/**
 * true/false
 *
 */
export type BooleanParameterValue = boolean;
/**
 * relative path from the playable.json to an image file
 *
 */
export type ImageParameterValue = string;
/**
 * A number
 *
 */
export type RangeParameterValue = number;
/**
 * Allowed select values
 *
 */
export type SelectParameterValue = string | number | boolean;
/**
 * relative path from the playable.json to an video file
 *
 */
export type VideoParameterValue = string;
/**
 * Type encapsulating all parameters definitions allowed to be used in an object
 *
 */
export type ObjectAllowedParameterDefinition = AlignmentParameterDefinition | AnimationParameterDefinition | Asset3DParameterDefinition | AudioParameterDefinition | BooleanParameterDefinition | ColorParameterDefinition | FontFamilyParameterDefinition | FormattedTextParameterDefinition | ImageParameterDefinition | NumberParameterDefinition | PositionParameterDefinition | RangeParameterDefinition | SelectParameterDefinition | TextParameterDefinition | VideoParameterDefinition;
/**
 * Any parameter value
 *
 */
export type ParameterValue = AlignmentParameterValue | AnimationParameterValue | Asset3DParameterValue | AudioParameterValue | BooleanParameterValue | ColorParameterValue | string | FormattedTextParameterValue | ImageParameterValue | NumberParameterValue | ObjectParameterValue | PositionParameterValue | RangeParameterValue | SelectParameterValue | TextParameterValue | VideoParameterValue;
/**
 * When used for default attribute this cannot be an object, default values will be derived from parameters definitions. Null can be used on default attribute to disable an optional object parameter
 *
 */
export type ObjectParameterValue = null | ObjectAllowedParameterValue;
/**
 * Type for keys in a parameter record
 *
 */
export type ParameterKey = string;
/**
 * List of allowed font family
 *
 * @devPortal
 *
 */
export type FontFamilyParameterValue = string;
/**
 * This interface describes the structure of the `playable.json` file.
 *
 * ## Declare parameters
 *
 * The playable.json must contain a json object containing a `parameters` key with the list of the parameters definitions for the playable.
 *
 * ```json
 * {
 *   "parameters": {
 *    "someTextParameter": {
 *      "type": "text",
 *      "label": "Short label",
 *      "default": "Nice text",
 *      "info": "Some additional information or longer description",
 *      "category": "Environment"
 *    }
 *  }
 * ```
 *
 * ## Retrieve parameters values
 *
 * The attribute name of the parameter is the key to use to retrieve the parameter value using the vsdk:
 *
 * ```typescript
 *  const someTextParameterValue = vsdk.getParameterValue<string>('someTextParameter');
 * ```
 *
 * @category playable.json
 * @devPortal
 */
export interface BuildConfiguration {
    $schema?: Schema;
    parameters: ParameterDefinitionRecord;
}
/**
 * Record of parameter definitions
 *
 */
export interface ParameterDefinitionRecord {
    [k: string]: ParameterDefinition;
}
/**
 * Alignment parameter definition
 *
 * vsdk.getParameterValue() returns either "left" | "center" | "right";
 *
 * _Note: The text parameter will display an alignment component on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface AlignmentParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    default: AlignmentParameterValue;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "alignment"
     */
    type: ParameterType.ALIGNMENT;
    highlightable?: HighlightParameterValue;
}
/**
 * Animation parameter definition
 *
 * vsdk.getParameterValue() returns a string representing an AnimationType.
 * Use allowedAnimations attribute to list supported AnimationTypes.
 *
 * _Note: The animation parameter will display a dropdown component listing available animations on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface AnimationParameterDefinition {
    allowedAnimations: AnimationType[];
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    default: AnimationParameterValue;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "animation"
     */
    type: ParameterType.ANIMATION;
    highlightable?: HighlightParameterValue;
}
/**
 * Animation parameter value
 *
 */
export interface AnimationParameterValue {
    animation: AnimationType;
    speed: number;
}
/**
 * Asset 3d parameter definition
 *
 * vsdk.getParameterValue() returns a `string` representing a base64 data URI ex: `data:application/octet-stream;base64,XXXXXX`
 *
 * 💡The default value must be `a relative path from the root to an existing asset 3d`
 *
 * _Note: The asset 3d parameter will display a `file picker` on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface Asset3DParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    default: Asset3DParameterValue;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "asset_3d"
     */
    type: ParameterType.ASSET_3D;
    highlightable?: HighlightParameterValue;
}
/**
 * Audio parameter definition
 *
 * vsdk.getParameterValue() returns a `string` representing a base64 data URI ex: `data:audio/mpeg;base64,XXXXXX`
 *
 * 💡The default value must be `a relative path from the root to an existing audio file`
 *
 * _Note: The audio parameter will display a `file picker` on Icecream UI._
 *
 * Accepted  s types
 *
 * | name | mime type  |
 * | ---- | ---------- |
 * | MP3  | audio/mpeg |
 *
 * @category Parameters
 *
 */
export interface AudioParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * relative path from the playable.json to an audio file
     */
    default: string;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "audio"
     */
    type: ParameterType.AUDIO;
    highlightable?: HighlightParameterValue;
}
/**
 * Boolean parameter definition
 *
 * vsdk.getParameterValue() returns a `boolean` for this parameter;
 *
 * _Note: The boolean parameter will display a `switch` on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface BooleanParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * true/false
     */
    default: boolean;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "boolean"
     */
    type: ParameterType.BOOLEAN;
    highlightable?: HighlightParameterValue;
}
/**
 * Color parameter definition
 *
 * vsdk.getParameterValue() returns a `string` representing a Hex (RGB) value (ex: `#000111`)
 *
 * _Note: The color parameter will display a `color picker` on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface ColorParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * HEX color
     */
    default: string;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "color"
     */
    type: ParameterType.COLOR;
    highlightable?: HighlightParameterValue;
}
/**
 * Font family parameter definition
 *
 * @category Parameters
 *
 */
export interface FontFamilyParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * List of allowed font family
     *
     * @devPortal
     */
    default: string;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "font_family"
     */
    type: ParameterType.FONT_FAMILY;
    highlightable?: HighlightParameterValue;
}
/**
 * Formatted Text parameter
 *
 * vsdk.getParameterValue() returns an `object` of type  {@link  FormattedTextParameterValue }
 *
 * @category Parameters
 *
 */
export interface FormattedTextParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    default: FormattedTextParameterValue;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "formatted_text"
     */
    type: ParameterType.FORMATTED_TEXT;
    highlightable?: HighlightParameterValue;
}
/**
 * Object representing values of all attributes of a formatted text parameter
 *
 */
export interface FormattedTextParameterValue {
    alignment: AlignmentParameterValue;
    fontColor: ColorParameterValue;
    /**
     * List of allowed font family
     *
     * @devPortal
     */
    fontFamily: string;
    fontSize: NumberParameterValue;
    strokeColor: ColorParameterValue;
    strokeWidth: NumberParameterValue;
    text: TextParameterValue;
}
/**
 * Image parameter definition
 *
 * vsdk.getParameterValue() returns a `string` representing a base64 data URI ex: `data:image/png;base64,XXXXXX`
 *
 * 💡The default value must be `a relative path from the root to an existing image`
 *
 * _Note: The image parameter will display a `file picker` and the image on Icecream UI._
 *
 * Accepted types
 *
 * | name | mime type  |
 * | ---- | ---------- |
 * | PNG  | image/png  |
 * | JPEG | image/jpeg |
 * | GIF  | image/gig  |
 *
 * @category Parameters
 *
 */
export interface ImageParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * relative path from the playable.json to an image file
     */
    default: string;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "image"
     */
    type: ParameterType.IMAGE;
    highlightable?: HighlightParameterValue;
}
/**
 * Number parameter definition
 *
 * vsdk.getParameterValue() returns a `number` for this parameter;
 *
 * _Note: The parameter will display a `text input` on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface NumberParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * A number
     */
    default: number;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "number"
     */
    type: ParameterType.NUMBER;
    highlightable?: HighlightParameterValue;
}
/**
 * Object parameter definition
 *
 * vsdk.getParameterValue() returns an `object` where attributes are the object parameters keys and values are the values of each parameters or null if the object is optional and deactivaled
 *
 * _Note: The object parameter will display the list of child parameters on Icecream UI._ _Note2: If optional is set to true, it will display a toggle to let the user deactivate the object._
 *
 * The list of allowed parameters is described in the  {@link  ObjectAllowedParameterDefinition }  type alias. Sub-parameters are defined using the a parameter definition
 *
 * @category Parameters
 *
 */
export interface ObjectParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    default?: null | ObjectAllowedParameterValue;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Objects can be marked as optional this will add a toggle to deactivate the parameter on icecream UI if the user deactivate the parameter vsdk.getParameterValue() will return null;
     */
    optional?: true;
    parameters: ObjectAllowedParameterDefinitionRecord;
    /**
     * Must be: "object"
     */
    type: ParameterType.OBJECT;
    highlightable?: HighlightParameterValue;
}
/**
 * Allowed values in an object (based on allowed parameter definitions)
 *
 */
export interface ObjectAllowedParameterValue {
    [k: string]: AlignmentParameterValue | AnimationParameterValue | Asset3DParameterValue | AudioParameterValue | BooleanParameterValue | ColorParameterValue | string | FormattedTextParameterValue | ImageParameterValue | NumberParameterValue | PositionParameterValue | RangeParameterValue | SelectParameterValue | TextParameterValue | VideoParameterValue | HighlightParameterValue;
}
/**
 * An object with an x and y attributes
 *
 */
export interface PositionParameterValue {
    x: number;
    y: number;
}
/**
 * Record of allowed parameter definitions
 *
 */
export interface ObjectAllowedParameterDefinitionRecord {
    [k: string]: ObjectAllowedParameterDefinition;
}
/**
 * Position parameter definition
 *
 * vsdk.getParameterValue() returns an `object` implementing the  {@link  PositionParameterValue }  interface
 *
 * ```typescript
 *  import { PositionParameterValue } from '@voodoo.io/playable-config'; const position = vsdk.getParameterValue<PositionParameterValue>('somePosition');
 *
 * console.log({ x: position.x, y: position.y });
 * ```
 *
 * @category Parameters
 *
 */
export interface PositionParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    default: PositionParameterValue;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "position"
     */
    type: ParameterType.POSITION;
    highlightable?: HighlightParameterValue;
}
/**
 * Range parameter definition
 *
 * vsdk.getParameterValue() returns a `number` for this parameter;
 *
 * _Note: The range parameter will display a `slider` on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface RangeParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * A number
     */
    default: number;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Maximum value for the range
     */
    max: number;
    /**
     * Minimum value for the range
     */
    min: number;
    /**
     * Increment value of the slider
     */
    step: number;
    /**
     * Must be: "range"
     */
    type: ParameterType.RANGE;
    highlightable?: HighlightParameterValue;
}
/**
 * Select parameter definition
 *
 * vsdk.getParameterValue() returns the `value` of the selected option;
 *
 * _Note: The select parameter will display a `dropdown` on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface SelectParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * Allowed select values
     */
    default: string | number | boolean;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Select options displayed in UI Name will be used as the label in the dropdown
     */
    options: SelectParameterOption[];
    /**
     * Must be: "select"
     */
    type: ParameterType.SELECT;
    highlightable?: HighlightParameterValue;
}
/**
 * Object with a name and value representing an option in a select
 *
 */
export interface SelectParameterOption {
    /**
     * Used as label in UI dropdown
     */
    name: string;
    value: SelectParameterValue;
}
/**
 * Text parameter definition
 *
 * vsdk.getParameterValue() returns a `string` for this parameter;
 *
 * _Note: The text parameter will display a `text input` on Icecream UI._
 *
 * @category Parameters
 *
 */
export interface TextParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * A string
     */
    default: string;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "text"
     */
    type: ParameterType.TEXT;
    highlightable?: HighlightParameterValue;
}
/**
 * Video parameter definition
 *
 * vsdk.getParameterValue() returns a `string` representing a base64 data URI ex: `data:video/mpeg;base64,XXXXXX`
 *
 * 💡The default value must be `a relative path from the root to an existing video`
 *
 * _Note: The video parameter will display a `file picker` and the video on Icecream UI._
 *
 * Accepted types
 *
 * | name | mime type  |
 * | ---- | ---------- |
 * | MP4  | video/mp4  |
 * | WEBM | video/webm  |
 *
 * @category Parameters
 *
 */
export interface VideoParameterDefinition {
    /**
     * Category use to group parameter on icecream
     */
    category?: string;
    /**
     * relative path from the playable.json to an video file
     */
    default: string;
    /**
     * Additional information for the icecream user
     */
    info?: string;
    /**
     * Label for the parameter form input
     */
    label: string;
    /**
     * Must be: "video"
     */
    type: ParameterType.VIDEO;
    highlightable?: HighlightParameterValue;
}
/**
 * Record of parameter values
 *
 */
export interface ParameterValueRecord {
    [k: string]: ParameterValue;
}
/**
 * Alignment parameter value
 *
 */
export declare enum AlignmentParameterValue {
    LEFT = "left",
    CENTER = "center",
    RIGHT = "right"
}
/**
 * Allowed animation types
 *
 * @devPortal
 *
 */
export declare enum AnimationType {
    NONE = "NONE",
    BOUNCE = "BOUNCE",
    SHAKE = "SHAKE",
    SWIPE_X_RIGHT = "SWIPE_X_RIGHT",
    SWIPE_X_LEFT = "SWIPE_X_LEFT",
    SWIPE_X_BOTH = "SWIPE_X_BOTH",
    SWIPE_Y_UP = "SWIPE_Y_UP",
    SWIPE_Y_DOWN = "SWIPE_Y_DOWN",
    SWIPE_Y_BOTH = "SWIPE_Y_BOTH",
    CLICK = "CLICK",
    HOLD = "HOLD",
    MOVE = "MOVE",
    RAINBOW = "RAINBOW",
    FADE = "FADE",
    TYPEWRITER = "TYPEWRITER",
    FADE_IN = "FADE_IN",
    FALL = "FALL"
}
/**
 * Enum of all parameter types
 * @devPortal
 *
 */
export declare enum ParameterType {
    ALIGNMENT = "alignment",
    ANIMATION = "animation",
    ASSET_3D = "asset_3d",
    AUDIO = "audio",
    BOOLEAN = "boolean",
    COLOR = "color",
    FONT_FAMILY = "font_family",
    FORMATTED_TEXT = "formatted_text",
    IMAGE = "image",
    NUMBER = "number",
    OBJECT = "object",
    POSITION = "position",
    RANGE = "range",
    SELECT = "select",
    TEXT = "text",
    VIDEO = "video"
}
/**
 * List of allowed font family
 *
 * @devPortal
 *
 */
export declare enum FontFamily {
    ARIAL = "Arial, sans-serif",
    VERDANA = "Verdana, sans-serif",
    TAHOMA = "Tahoma, sans-serif",
    TREBUCHET = "Trebuchet MS, sans-serif",
    TIMES_NEW_ROMAN = "Times New Roman, serif",
    GEORGIA = "Georgia, serif",
    GARAMOND = "Garamond, serif",
    COURIER_NEW = "Courier New, monospace",
    BRUSH_SCRIPT = "Brush Script MT, cursive"
}
